In [ ]:
# orthogonal case
l_a = 1.0
l_b = 1.8
l_c = 1.4

lattice = np.array([[l_a, 0, 0], [0, l_b, 0], [0, 0, l_c]])

def get_system_size():
    # Get the size of the cell.
    system_size = [
        L * ANGSTROM for L in [l_a, l_b, l_c]   
    ]
    if n_grid_def == "density":
        grid_size = [
            int(L / ANGSTROM * n_grid) for L in system_size
        ]  # int always rounds down
    elif n_grid_def == "value":
        grid_size = [n_grid, n_grid, n_grid]
    grid = np.zeros(
        [grid_size[0], grid_size[1], grid_size[2], 3]
    )
    for i in range(grid_size[0]):
        for j in range(grid_size[1]):
            for k in range(grid_size[2]):
                grid[i, j, k] = (
                    i / grid_size[0] * lattice[0]
                    + lattice[0] / (2 * grid_size[0])
                    + j / grid_size[1] * lattice[1]
                    + lattice[1] / (2 * grid_size[1])
                    + k / grid_size[2] * lattice[2]
                    + lattice[2] / (2 * grid_size[2])
                )
    return grid

get_system_size()

In [15]:
import pandas as pd
import numpy as np
x = pd.read_csv('zz_results/RSM0107_grid_7_3_2_raspa.csv')
x2 = pd.read_csv('zz_results/RSM0107_grid_7_3_2_new_tail_k.csv')

In [5]:
x

,X,Y,Z,energy,LJ,Coulomb_ewald,Coulomb_real,Coulomb_fourier,alpha
0,0.221819,0.359594,0.223101,-16747.411067,-769.680188,-15977.730879,-1634.080451,-14343.650428,0.341429
1,0.111853,0.571032,0.669303,-16789.184948,-838.127813,-15951.057135,-1898.392140,-14052.664995,0.341429
2,0.001886,0.782471,1.115504,-16745.708177,-952.323503,-15793.384675,-2262.336532,-13531.048143,0.341429
3,-0.108081,0.993910,1.561706,-16474.001263,-1120.904355,-15353.096909,-2618.015942,-12735.080966,0.341429
4,-0.218047,1.205348,2.007908,-15793.946689,-1346.323897,-14447.622792,-2826.130930,-11621.491862,0.341429
...,...,...,...,...,...,...,...,...,...
5563,2.032609,17.112335,10.931944,-15776.324515,-1350.433673,-14425.890842,-2800.154107,-11625.736735,0.341429
5564,1.922642,17.323774,11.378146,-16460.231374,-1121.878056,-15338.353318,-2597.404007,-12740.949311,0.341429
5565,1.812675,17.535213,11.824347,-16737.085657,-950.907264,-15786.178393,-2248.013394,-13538.164999,0.341429
5566,1.702709,17.746652,12.270549,-16783.821508,-835.459028,-15948.362480,-1888.187546,-14060.174934,0.341429
5567,1.592742,17.958090,12.716751,-16741.304924,-766.584516,-15974.720407,-1624.042606,-14350.677801,0.341429

In [6]:
x2

,X,Y,Z,energy,LJ,Coulomb_ewald,Coulomb_real,Coulomb_fourier,alpha,tail_correction,k_vec
0,0.221819,0.359594,0.223101,-16747.411067,-769.680188,-15977.730879,-1634.080451,-14343.650428,0.341429,-26248.85905,13;16;13
1,0.111853,0.571032,0.669303,-16789.184948,-838.127813,-15951.057135,-1898.392140,-14052.664995,0.341429,-26248.85905,13;16;13
2,0.001886,0.782471,1.115504,-16745.708177,-952.323503,-15793.384675,-2262.336532,-13531.048143,0.341429,-26248.85905,13;16;13
3,-0.108081,0.993910,1.561706,-16474.001263,-1120.904355,-15353.096909,-2618.015942,-12735.080966,0.341429,-26248.85905,13;16;13
4,-0.218047,1.205348,2.007908,-15793.946689,-1346.323897,-14447.622792,-2826.130930,-11621.491862,0.341429,-26248.85905,13;16;13
...,...,...,...,...,...,...,...,...,...,...,...
5563,2.032609,17.112335,10.931944,-15776.324515,-1350.433673,-14425.890842,-2800.154107,-11625.736735,0.341429,-26248.85905,13;16;13
5564,1.922642,17.323774,11.378146,-16460.231374,-1121.878056,-15338.353318,-2597.404007,-12740.949311,0.341429,-26248.85905,13;16;13
5565,1.812675,17.535213,11.824347,-16737.085657,-950.907264,-15786.178393,-2248.013394,-13538.164999,0.341429,-26248.85905,13;16;13
5566,1.702709,17.746652,12.270549,-16783.821508,-835.459028,-15948.362480,-1888.187546,-14060.174934,0.341429,-26248.85905,13;16;13
5567,1.592742,17.958090,12.716751,-16741.304924,-766.584516,-15974.720407,-1624.042606,-14350.677801,0.341429,-26248.85905,13;16;13

In [13]:
# check if equal
x2[["X", "Y", "Z", "energy", "LJ", "Coulomb_ewald", "Coulomb_real", "Coulomb_fourier"]] == x[["X", "Y", "Z", "energy", "LJ", "Coulomb_ewald", "Coulomb_real", "Coulomb_fourier"]]

,X,Y,Z,energy,LJ,Coulomb_ewald,Coulomb_real,Coulomb_fourier
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
5563,True,True,True,True,True,True,True,True
5564,True,True,True,True,True,True,True,True
5565,True,True,True,True,True,True,True,True
5566,True,True,True,True,True,True,True,True
5567,True,True,True,True,True,True,True,True

In [16]:
for key in ["X", "Y", "Z", "energy", "LJ", "Coulomb_ewald", "Coulomb_real", "Coulomb_fourier"]:
    print(key)
    print(np.allclose(x2[key], x[key], rtol=1e-5, atol=1e-5))

X
True
Y
True
Z
True
energy
True
LJ
True
Coulomb_ewald
True
Coulomb_real
True
Coulomb_fourier
True